### ISSUE TITLE
npy file is not available

### ISSUE THREAD

**Issue by ycjing** [janivanecky/Artistic-Style#1]
When I opened the link https://dl.dropboxusercontent.com/u/50333326/vgg19.npy to download the "npy file", there was an error message "This account's links are generating too much traffic and have been temporarily disabled!". 
Is there a new link available? Thanks!

**Comment by janivanecky** [comment]
Oh, ok. The numpy file was created by [Chris](https://github.com/machrisaa/), so it's his dropbox storage. I've already asked him if it would be alright to reupload it somewhere where it won't get blocked due the traffic. As soon as he agrees I'll reupload the numpy file and post a new link.

**Comment by janivanecky** [comment]
Chris uploaded the file to [Mega](https://mega.nz/#!xZ8glS6J!MAnE91ND_WyfZ_8mvkuSa2YcA7q-1ehfSm-Q1fxOvvs). I've updated the link in the README.

**Comment by ycjing** [comment]
Thanks!
