### ISSUE TITLE
TypeError: expand_dims() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by ycjing** [janivanecky/Artistic-Style#2]
The code is wonderful and I'm using python 2.7 to run the code.  
It outputs the error message: File "/home/jyc/2thPaper_TensorFlow/Artistic-Style-master/vgg.py", line 20, in __init__self.data_dict = np.load(vgg19_npy_path, encoding='latin1').item(). TypeError: load() got an unexpected keyword argument 'encoding' at first. I guess it's due to the python version I used after I refer to http://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html. The code may be developed under python 3.x. So I remove "encoding='latin1'" and it works.

But then I get another error message: "File "style.py", line 111, in <module>input_image = tf.Variable(np.expand_dims(images[0,:,:,:])) TypeError: expand_dims() takes exactly 2 arguments (1 given)"
I wonder if someone has the same error message.

Thanks!

**Comment by janivanecky** [comment]
Which version of Tensorflow do you use?

**Comment by ycjing** [comment]
@janivanecky The lastest version, tensorflow-0.10.0

**Comment by janivanecky** [comment]
I also used python2.7 and the same version of Tensorflow. You may be using different version of numpy. I'm using version 1.11.

**Comment by kumekay** [comment]
@janivanecky, @ycjing is right according to numpy docs this function requires 2 args
http://docs.scipy.org/doc/numpy/reference/generated/numpy.expand_dims.html

So, the fix is `input_image = tf.Variable(np.expand_dims(images[0,:,:,:], 0))`

**Comment by janivanecky** [comment]
True, I must have accidentally commited untested version of the file. Thanks for pointing that out @ycjing and thanks for pulling the fix @pinya, I've merged the request.
